### PR TITLE
Some changes I made

### PR DESCRIPTION
**Pull request by Bytekeeper**
Hi,

here's a PR of things I changed. If you want I can make more specific PRs for smaller issues, but I tried to follow the general "tenor" of the code.
I'll be on vacaction next week, but if there are things I should change before a merge, I can do them after the week.

### CODE REVIEW

**Comment by adakitesystems** [comment]
Hello!

I have merged all of these commits into branch [develop](https://github.com/openbw/bwapi4j/tree/develop) and I will be working on that branch until @IMP-42 has a chance to review these changes. This PR contains several critical bug fixes that I would like to use immediately.

I have gone through all of the commits and believe if any commits require modification, they can be discussed and modified via additional commits at a later date.

Thank you for all your hard work, @Bytekeeper! This PR is much appreciated. Enjoy your vacation!

This PR may remain open for now until reviewed by @IMP-42.

**Comment by adakitesystems** [comment]
Below is my review. Any commit not mentioned is either good in my opinion or should be reviewed by @IMP-42.

#### Added Weapon abstraction and "Armed" interfacte to indicate combat units including Photon Cannon and Sunken Colonies
https://github.com/OpenBW/BWAPI4J/pull/15/commits/1f814c62a4453a9a15d9373e475ea28cc01fa434

- I like this idea. What is everyone's thoughts about breaking up the `Armed` interface into two more interfaces? Rename `Armed` to `Attacker` then have `GroundAttacker` and `AirAttacker`. `GroundAttacker` will provide `getGroundWeapon()` and `AirAttacker` will provide `getAirWeapon()`?

#### Added getDistance to TilePosition and "fixed" Position.getDistance to use the algorithm BW uses
https://github.com/OpenBW/BWAPI4J/pull/15/commits/27d1fef0cabd00f774f6f04dffdd71615d3bc0b5

- I will have to look into it further, but I thought BWAPI has `getApproxDistance` and also `getDistance`? Should we provide both?

#### Added common base class for Workers and "isWalkable(WalkPosition)" 
https://github.com/OpenBW/BWAPI4J/pull/15/commits/3807f8e18e09f5d557be486c0cb04517f376dbd3

- This is a good idea. As discussed in this post: https://github.com/OpenBW/BWAPI4J/issues/10, maybe we should remove the generic type from the `Worker` class definition? I.e. `Worker<Extractor>` to `Worker`?

#### getDistance should work for hidden units too. 
https://github.com/OpenBW/BWAPI4J/pull/15/commits/27334a8c87d7c1ae5903efd57d56314e674ee09f

- I will have to look into it further, but there is not much information available from hidden/non-existing units. Please clarify the removal of these checks. For optimization reasons?
- In regards to the added comment on line 7: `Arclite_Shock_Cannon_Hit(150), // 143 actually`, please clarify. In the BWAPI sources, it is 150. See attached screenshot. Have you contradictory evidence?
arclite_shock_cannon_hit

#### Allow custom user data for units, easier than forcing clients to use maps.
https://github.com/OpenBW/BWAPI4J/pull/15/commits/d7a3e98b33745bd592f5e5d18c62e28e1b6a5381

- I think this is a good idea but I am not fond of it. I do not have a good alternative. Any further comments/suggestions?

#### Positions outside of the map are not walkable. 
https://github.com/OpenBW/BWAPI4J/pull/15/commits/86d62d4862b63b01a196050265a479cd24ce00df

- I disagree with the added checks in `isWalkable`. The behavior of `isWalkable` should be similar to `collection.get(-1)` in that an exception should be thrown for bad input parameters. Please provide a counter to my argument.

#### Things can't be researched/upgraded while being researched/upgraded 
https://github.com/OpenBW/BWAPI4J/pull/15/commits/b1fa8ffb0c7e2ba3541876b281b6e90f90e1e6f3

- This is true, but I am not sure `canResearch/canUpgrade` should be modified to reflect this. Please clarify the purpose of this change. Would the user be negatively affected if `canResearch/canUpgrade` returned true for something already in progress?

#### Add a way to determine if a unit provides supply. 
https://github.com/OpenBW/BWAPI4J/pull/15/commits/250db561e7651fc6859c0169b74b2697d04022ff

- I like this idea. However, all of the "main halls" (i.e. Command Center, Hatchery, Lair, Hive, Nexus) provide additional supply, too. It's also worth noting that the main halls each of each race provide a different amount of supply. Please clarify the benefit of this change. Does it help the user determine which building to construct when running out of supply? Obviously, the user wouldn't want to construct a Command Center if running out of supply. In such a case, adding the `SupplyProvider` attribute to the main halls would not be beneficial. Comments/thoughts/suggestions on adding the `SupplyProvider` attribute to main halls?

#### Small helper functions to make calls to "type()" obsolete. 
https://github.com/OpenBW/BWAPI4J/pull/15/commits/c32a50ce06cbe81e62e04abc34a78de7bd0bfbac

- Can we now remove or make the method `type()` private? @IMP-42?

**Comment by Bytekeeper** [comment]
#### Added getDistance to TilePosition and "fixed" Position.getDistance to use the algorithm BW uses
Maybe "both" would be useful, but I also check the code of OpenBW and it uses the same approx distance routine - so adding a "correct" distance function might be counter-intuitive.

#### getDistance should work for hidden units too.
The code did return "MAX_INT" before, but the stored position == "last known position" which allows bots to use "normal" and "hidden" Units the same way for "range checks" etc.

#### Allow custom user data for units, easier than forcing clients to use maps.
I also don't like it that much as it requires casting. But the alternatives are sub-classing which is kind of overkill (imo) or using an indirect approach: Map<Unit,MyData>. Maybe someone has a better idea?

The Arclite thing: When debugging it reported strange Bullet types for Tanks and Lurkers, so I made that change/comment. But I could also be wrong, I guess that should be reverted.

#### Things can't be researched/upgraded while being researched/upgraded
The negative effect is:
* Bot checks: Can I research
* Yes? Then research!
* Ah darn, the research command failed (because it was already in research)
* rince repeat

**Comment by adakitesystems** [comment]
Everything looks great. Thank you once again for all the changes, @Bytekeeper!

**Pull request merged**
