### PR TITLE
Implement "List<UnitType> Trainer.getTrainingQueue()"

### PR DESCRIPTION
**Pull request by adakitesystems**
I do not like this approach that much but I am not aware of another way to do it while retaining/improving performance. Any ideas?

Note: This PR is yet to be tested.

### CODE REVIEW

**Comment by Bytekeeper** [comment]
Since you also want to be able to cancel elements, maybe using `List<TrainingSlot> getTr....` would be better? And the `TrainingSlot` could have the unit type (for now) and a `cancel()`?

**Comment by adakitesystems** [comment]
Good point and idea about canceling training slots. I see there is already a `Trainer.cancelTrain(int slot)`. With your suggestion, this method should be removed from the Trainer and `TrainingSlot` should hold both the UnitType and the slot number. Then, the `cancel()` method can issue a command to cancel the internal training slot. I'll make a commit and we can see how it looks.

**Comment by adakitesystems** [comment]
I like the idea but I might dislike the way I implemented this. I decided to leave the `cancel(int slot)`. Maybe it should still be removed. Overall comments/review?

**Comment by adakitesystems** [comment]
Updated the last commit. IMO it looks much better now. Thanks @Bytekeeper for the suggestions.

**Pull request merged**
